// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file filesystem.proto (package fs, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file filesystem.proto.
 */
export const file_filesystem: GenFile =
  /*@__PURE__*/
  fileDesc(
    "ChBmaWxlc3lzdGVtLnByb3RvEgJmcyKAAQoQRmlsZVN5c3RlbU9iamVjdBIMCgRuYW1lGAEgASgJEhgKBGZpbGUYAyABKAsyCC5mcy5GaWxlSAASIgoJZGlyZWN0b3J5GAQgASgLMg0uZnMuRGlyZWN0b3J5SAASGAoEbGluaxgFIAEoCzIILmZzLkxpbmtIAEIGCgR0eXBlIjUKBEZpbGUSDAoEc2l6ZRgBIAEoAxIfCgZoYXNoZXMYAiABKAsyDy5mcy5DaHVua0hhc2hlcyIuCgtDaHVua0hhc2hlcxIRCgljaHVua1NpemUYASABKAUSDAoEaGFzaBgCIAMoDCIcCglEaXJlY3RvcnkSDwoHZW50cmllcxgBIAMoDCIbCgRMaW5rEhMKC3RhcmdldF9wYXRoGAEgASgJIkQKDk9iamVjdFdpdGhIYXNoEiQKBm9iamVjdBgBIAEoCzIULmZzLkZpbGVTeXN0ZW1PYmplY3QSDAoEaGFzaBgCIAEoDGIGcHJvdG8z",
  );

/**
 * @generated from message fs.FileSystemObject
 */
export type FileSystemObject = Message<"fs.FileSystemObject"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from oneof fs.FileSystemObject.type
   */
  type:
    | {
        /**
         * @generated from field: fs.File file = 3;
         */
        value: File;
        case: "file";
      }
    | {
        /**
         * @generated from field: fs.Directory directory = 4;
         */
        value: Directory;
        case: "directory";
      }
    | {
        /**
         * @generated from field: fs.Link link = 5;
         */
        value: Link;
        case: "link";
      }
    | { case: undefined; value?: undefined };
};

/**
 * Describes the message fs.FileSystemObject.
 * Use `create(FileSystemObjectSchema)` to create a new message.
 */
export const FileSystemObjectSchema: GenMessage<FileSystemObject> =
  /*@__PURE__*/
  messageDesc(file_filesystem, 0);

/**
 * @generated from message fs.File
 */
export type File = Message<"fs.File"> & {
  /**
   * @generated from field: int64 size = 1;
   */
  size: bigint;

  /**
   * @generated from field: fs.ChunkHashes hashes = 2;
   */
  hashes?: ChunkHashes;
};

/**
 * Describes the message fs.File.
 * Use `create(FileSchema)` to create a new message.
 */
export const FileSchema: GenMessage<File> =
  /*@__PURE__*/
  messageDesc(file_filesystem, 1);

/**
 * @generated from message fs.ChunkHashes
 */
export type ChunkHashes = Message<"fs.ChunkHashes"> & {
  /**
   * @generated from field: int32 chunkSize = 1;
   */
  chunkSize: number;

  /**
   * @generated from field: repeated bytes hash = 2;
   */
  hash: Uint8Array[];
};

/**
 * Describes the message fs.ChunkHashes.
 * Use `create(ChunkHashesSchema)` to create a new message.
 */
export const ChunkHashesSchema: GenMessage<ChunkHashes> =
  /*@__PURE__*/
  messageDesc(file_filesystem, 2);

/**
 * @generated from message fs.Directory
 */
export type Directory = Message<"fs.Directory"> & {
  /**
   * @generated from field: repeated bytes entries = 1;
   */
  entries: Uint8Array[];
};

/**
 * Describes the message fs.Directory.
 * Use `create(DirectorySchema)` to create a new message.
 */
export const DirectorySchema: GenMessage<Directory> =
  /*@__PURE__*/
  messageDesc(file_filesystem, 3);

/**
 * @generated from message fs.Link
 */
export type Link = Message<"fs.Link"> & {
  /**
   * (for now) we can't target hashes in some cases (e.g., linking to ancestor causes a cycle), so this will have to do
   *
   * @generated from field: string target_path = 1;
   */
  targetPath: string;
};

/**
 * Describes the message fs.Link.
 * Use `create(LinkSchema)` to create a new message.
 */
export const LinkSchema: GenMessage<Link> =
  /*@__PURE__*/
  messageDesc(file_filesystem, 4);

/**
 * @generated from message fs.ObjectWithHash
 */
export type ObjectWithHash = Message<"fs.ObjectWithHash"> & {
  /**
   * @generated from field: fs.FileSystemObject object = 1;
   */
  object?: FileSystemObject;

  /**
   * @generated from field: bytes hash = 2;
   */
  hash: Uint8Array;
};

/**
 * Describes the message fs.ObjectWithHash.
 * Use `create(ObjectWithHashSchema)` to create a new message.
 */
export const ObjectWithHashSchema: GenMessage<ObjectWithHash> =
  /*@__PURE__*/
  messageDesc(file_filesystem, 5);
