// @generated by protobuf-ts 2.9.6
// @generated from protobuf file "rpc/uiservice.proto" (package "Ui", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { Ui } from "./uiservice";
import type { DataUsage } from "../rpc_common";
import type { UsageRequest } from "./uiservice";
import type { SearchResponse } from "../rpc_common";
import type { SearchRequest } from "./uiservice";
import type { ServerStreamingCall } from "@protobuf-ts/runtime-rpc";
import type { String$ } from "./uiservice";
import type { DownloadContainerOptions } from "./uiservice";
import type { PublishingOptions } from "./uiservice";
import type { ObjectFromDiskOptions } from "./uiservice";
import type { ObjectList } from "../fs/filesystem";
import type { Guid } from "../rpc_common";
import type { Progress } from "./uiservice";
import type { GuidList } from "../rpc_common";
import type { Empty } from "../rpc_common";
import type { Hash } from "../rpc_common";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { Path } from "./uiservice";
import type { ObjectOptions } from "./uiservice";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service Ui.Ui
 */
export interface IUiClient {
    /**
     * @generated from protobuf rpc: PickObjectPath(Ui.ObjectOptions) returns (Ui.Path);
     */
    pickObjectPath(input: ObjectOptions, options?: RpcOptions): UnaryCall<ObjectOptions, Path>;
    /**
     * @generated from protobuf rpc: GetObjectPath(rpc_common.Hash) returns (Ui.Path);
     */
    getObjectPath(input: Hash, options?: RpcOptions): UnaryCall<Hash, Path>;
    /**
     * @generated from protobuf rpc: RevealObjectInExplorer(rpc_common.Hash) returns (rpc_common.Empty);
     */
    revealObjectInExplorer(input: Hash, options?: RpcOptions): UnaryCall<Hash, Empty>;
    /**
     * @generated from protobuf rpc: GetAllContainers(rpc_common.Empty) returns (rpc_common.GuidList);
     */
    getAllContainers(input: Empty, options?: RpcOptions): UnaryCall<Empty, GuidList>;
    /**
     * @generated from protobuf rpc: GetDownloadProgress(rpc_common.Hash) returns (Ui.Progress);
     */
    getDownloadProgress(input: Hash, options?: RpcOptions): UnaryCall<Hash, Progress>;
    /**
     * @generated from protobuf rpc: GetContainerObjects(rpc_common.Guid) returns (fs.ObjectList);
     */
    getContainerObjects(input: Guid, options?: RpcOptions): UnaryCall<Guid, ObjectList>;
    /**
     * @generated from protobuf rpc: GetContainerRootHash(rpc_common.Guid) returns (rpc_common.Hash);
     */
    getContainerRootHash(input: Guid, options?: RpcOptions): UnaryCall<Guid, Hash>;
    /**
     * @generated from protobuf rpc: ImportObjectFromDisk(Ui.ObjectFromDiskOptions) returns (rpc_common.Guid);
     */
    importObjectFromDisk(input: ObjectFromDiskOptions, options?: RpcOptions): UnaryCall<ObjectFromDiskOptions, Guid>;
    /**
     * @generated from protobuf rpc: PublishToTracker(Ui.PublishingOptions) returns (rpc_common.Empty);
     */
    publishToTracker(input: PublishingOptions, options?: RpcOptions): UnaryCall<PublishingOptions, Empty>;
    /**
     * @generated from protobuf rpc: DownloadContainer(Ui.DownloadContainerOptions) returns (rpc_common.Empty);
     */
    downloadContainer(input: DownloadContainerOptions, options?: RpcOptions): UnaryCall<DownloadContainerOptions, Empty>;
    /**
     * @generated from protobuf rpc: PauseContainerDownload(rpc_common.Guid) returns (rpc_common.Empty);
     */
    pauseContainerDownload(input: Guid, options?: RpcOptions): UnaryCall<Guid, Empty>;
    /**
     * @generated from protobuf rpc: ResumeContainerDownload(rpc_common.Guid) returns (rpc_common.Empty);
     */
    resumeContainerDownload(input: Guid, options?: RpcOptions): UnaryCall<Guid, Empty>;
    /**
     * @generated from protobuf rpc: CopyToClipboard(Ui.String) returns (rpc_common.Empty);
     */
    copyToClipboard(input: String$, options?: RpcOptions): UnaryCall<String$, Empty>;
    /**
     * @generated from protobuf rpc: SearchForObjects(Ui.SearchRequest) returns (stream rpc_common.SearchResponse);
     */
    searchForObjects(input: SearchRequest, options?: RpcOptions): ServerStreamingCall<SearchRequest, SearchResponse>;
=======
  /**
   * @generated from protobuf rpc: PickObjectPath(Ui.ObjectOptions) returns (Ui.Path);
   */
  pickObjectPath(
    input: ObjectOptions,
    options?: RpcOptions,
  ): UnaryCall<ObjectOptions, Path>;
  /**
   * @generated from protobuf rpc: GetObjectPath(rpc_common.Hash) returns (Ui.Path);
   */
  getObjectPath(input: Hash, options?: RpcOptions): UnaryCall<Hash, Path>;
  /**
   * @generated from protobuf rpc: RevealObjectInExplorer(rpc_common.Hash) returns (rpc_common.Empty);
   */
  revealObjectInExplorer(
    input: Hash,
    options?: RpcOptions,
  ): UnaryCall<Hash, Empty>;
  /**
   * @generated from protobuf rpc: GetAllContainers(rpc_common.Empty) returns (rpc_common.GuidList);
   */
  getAllContainers(
    input: Empty,
    options?: RpcOptions,
  ): UnaryCall<Empty, GuidList>;
  /**
   * @generated from protobuf rpc: GetDownloadProgress(rpc_common.Hash) returns (Ui.Progress);
   */
  getDownloadProgress(
    input: Hash,
    options?: RpcOptions,
  ): UnaryCall<Hash, Progress>;
  /**
   * @generated from protobuf rpc: GetContainerObjects(rpc_common.Guid) returns (fs.ObjectList);
   */
  getContainerObjects(
    input: Guid,
    options?: RpcOptions,
  ): UnaryCall<Guid, ObjectList>;
  /**
   * @generated from protobuf rpc: GetContainerRootHash(rpc_common.Guid) returns (rpc_common.Hash);
   */
  getContainerRootHash(
    input: Guid,
    options?: RpcOptions,
  ): UnaryCall<Guid, Hash>;
  /**
   * @generated from protobuf rpc: ImportObjectFromDisk(Ui.ObjectFromDiskOptions) returns (rpc_common.Guid);
   */
  importObjectFromDisk(
    input: ObjectFromDiskOptions,
    options?: RpcOptions,
  ): UnaryCall<ObjectFromDiskOptions, Guid>;
  /**
   * @generated from protobuf rpc: PublishToTracker(Ui.PublishingOptions) returns (rpc_common.Empty);
   */
  publishToTracker(
    input: PublishingOptions,
    options?: RpcOptions,
  ): UnaryCall<PublishingOptions, Empty>;
  /**
   * @generated from protobuf rpc: DownloadContainer(Ui.DownloadContainerOptions) returns (rpc_common.Empty);
   */
  downloadContainer(
    input: DownloadContainerOptions,
    options?: RpcOptions,
  ): UnaryCall<DownloadContainerOptions, Empty>;
  /**
   * @generated from protobuf rpc: PauseContainerDownload(rpc_common.Guid) returns (rpc_common.Empty);
   */
  pauseContainerDownload(
    input: Guid,
    options?: RpcOptions,
  ): UnaryCall<Guid, Empty>;
  /**
   * @generated from protobuf rpc: ResumeContainerDownload(rpc_common.Guid) returns (rpc_common.Empty);
   */
  resumeContainerDownload(
    input: Guid,
    options?: RpcOptions,
  ): UnaryCall<Guid, Empty>;
  /**
   * @generated from protobuf rpc: CopyToClipboard(Ui.String) returns (rpc_common.Empty);
   */
  copyToClipboard(
    input: String$,
    options?: RpcOptions,
  ): UnaryCall<String$, Empty>;
  /**
   * @generated from protobuf rpc: SearchForObjects(Ui.SearchRequest) returns (stream rpc_common.SearchResponse);
   */
  searchForObjects(
    input: SearchRequest,
    options?: RpcOptions,
  ): ServerStreamingCall<SearchRequest, SearchResponse>;
  /**
   * @generated from protobuf rpc: GetDataUsage(Ui.UsageRequest) returns (rpc_common.DataUsage);
   */
  getDataUsage(
    input: UsageRequest,
    options?: RpcOptions,
  ): UnaryCall<UsageRequest, DataUsage>;
}
